### ISSUE TITLE
Shopping v2 improvements

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#1649]
technical 

- [x] ~~cache "check" requests in service worker when device is offline and sync later @vabene1111~~ (moved to next milestone #1761)
- [x] saved supermarket lost sometimes
- [x] unedefined sorted bottom when no supermarkt is selected

UI

- [x] ~~try drag&drop category change~~ (removed in favor of swiping)
- [x] try swipe actions to delay/set checked/whatever would be useful as swipe action
- [x] confirmation on category delete in supermarket tab @Kaibu
- [x] several ideas maybe some duplicates https://github.com/TandoorRecipes/recipes/issues/1427
- [x] properly handle the height of the inner list container in relation to the bottom buttons to prevent overlapping
- [x] make supermarket edit page more easy to understand
- [x] changes to the description field of supermarkets doesn't save in editing (but works in creating new ones)
- [x] supermarket descriptions should probably be shown in "supermarkets" tab
- [x] ~~Add undo (some kind of list with last checked entries to uncheck them again)~~ (moved to next milestone #1760)

deprecate old

- [x] app manifest link 
- [x] tables / filter
