### ISSUE TITLE
Shopping List v2

### ISSUE THREAD

**Issue by vabene1111** [TandoorRecipes/recipes#893]
Even though the old rework issue is not even finished rework v2 is in our minds. Collecting TODO's and other open issues here.

### New Concept
One list with all open entries, supermarkets act as a "Filter" on all open entries so you can see the items available at the supermarket you are going to (question here: how to handle uncategorized entries)

### Old related issues / todos pre-existent to new concept

- [x] Issue of last rework #114 not all features need to be implemented, some are just inspiration/hint at how it might be used
- [x] Merge ingredients with no unit #680
- [x] several ideas #490
- [x] fix scaling https://github.com/vabene1111/recipes/issues/453#issuecomment-820664755 this probably requires some database refactoring as well as the old system wasn't developed to handle the servings system. 
- [x] moving entries to categories is annoying with large lists especially on mobile
- [x] comprehensive tests

Related issues possible after rework is done
- add to list when cooking #710

## CLEANUP ACTIVITIES
- [x] Delete supermarket in shopping list
- [x] Create supermarket populates entry with json of new supermarket
- [x] fix supermarket categories in Edit Supermarket Modal in ModelListView 
- [x] fix filter to supermarket setting
- [x] add shopping entry hidden when shopping list is empty
- [x] fix filter_to_supermarket setting (missing in form post?)
- [x] recipe supermarket view - default to checking items or add select all button
- [x] fix Unchecking / checking detailed entries
- [x] Fix responsive display of add entry
- [x] merge ignore_shopping and on-hand
- [x] switch inherited fields to be inclusive everywhere
- [x] complete all entries in a group-by context menu #1187 
- [x] delay all entries in a group-by context menu
- [x] delete all entries in a group-by context menu
- [x] on-hand all entries in a group-by context menu
- [x] setting to mark completed entries as on-hand automatically
- [x] fix filter to supermarket category only #1185 
- [x] Clear new item after add
- [x] error saving old shoppinglist
- [x] supermarket ordering not working
- [x] 'ingredient parser' entry for new shopping list
- [x] move undefined categories to top of list
- [x] make onhand multi-user

**Comment by smilerz** [comment]
- [ ] Bring integration #911 
- [ ] Amazon Alexa integration

**Comment by smilerz** [comment]
- [ ] Foods in tree inherit shopping category
- [ ] Setting in foods to ignore inheritance
- [ ] add food that are part of food recipe and or step recipe #338 
- [ ] anonymous sharing of shopping list
- [ ] option to limit supermarket to category
- [ ] add new entry from shopping list view
- [ ] add non-food shopping list entry
- [ ] view ingredient notes
- [ ] move entry to 'next trip'
- [ ] option to show/hide uncategorized and/or categories
- [ ] view meal plan notes #131 
- [ ] merge food into single line
- [ ] optional unit conversion
- [ ] optional shopping purchase unit (flour is bought in 3 pound bags, but used in much smaller units)
- [ ] shopping list sort order (at least two levels) #680 
- [ ] download as CSV
- [ ] download as PDF
- [ ] copy as table
- [ ] export to Google Sheets
- [ ] edit supermarket category from shopping list
- [ ] edit shopping/on-hand from recipe
- [ ] add multiple meal plans/days from meal plan view
- [ ] tests, tests, tests

**Comment by smilerz** [comment]
@vabene1111 - what does this do?  and why?  (it's in the current shopping list)

`export_text_prefix: '', //TODO add userpreference`

**Comment by vabene1111** [comment]
its a prefix that gets added before each line in the export modal. It can be used to for example export a markdown list (by using prefix `- [ ] `). This was meant to allow people to easily move the data to some other app supporting markdown or some other kind of list formatting.

**Comment by smilerz** [comment]
Summary of what this release includes:
1. Single continuous shopping list
2. Track food you already have
3. Food inherit supermarket categories
4. Food inherit 'ignore shopping' (never shop for this item e.g. water)
5. Manually or Automatically add meal plan recipe to shopping list
6. Automatically skip adding food to the shopping list if you already have it on hand
7. Add related recipes (food recipes or step recipes) to shopping list
8. Add/remove food to shopping list from view recipe page
9. Add/remove food to 'on hand' from the recipe page
10. New & improved Add to Shopping Modal screen
11. Share your shopping list with another user, no need to remember to share it each time.

**Comment by vabene1111** [comment]
UI tweaks @Kaibu and i will take a look at 

- [ ] compact mode (using less vertical space and optimizing more for mobile)
- [ ] large mode mobile optimization
- [ ] try drag&drop category change
- [ ] try swipe actions to delay/set checked/whatever would be useful as swipe action
- [ ] reduce vertical space of supermarket cards in supermarket configurator 
- [ ] align and standardize style of input boxes for both quick and normal ingredient input
- [ ] show checkboxes on the right table side if on mobile or make this a setting (with flexbox maybe)
- [ ] right align filter popover when clicking it

**Comment by vabene1111** [comment]
- [ ] make "auto on hand" false by default
- [ ] @Kaibu fix right click menu opening even when clicking the details link (my bad for having the idea with the click everywhere, i think thats not good)
- [ ] add a way to put a recipe on the list from the shoping page

**Comment by Kaibu** [comment]
- [ ] Add undo
- [ ] Dots hardly usable on mobile
- [ ] Auto sync desync fix from old list

**Comment by smilerz** [comment]
@Kaibu the lag on checked is probably because the item isn't 'checked' until after the API call - this could be moved up and reversed if the API call fails

**Comment by vabene1111** [comment]
Ah I see, I think I saw your comment on that. I think that can be reversed because if you check it it should definitely be checked and if the request really fails things are fucked anyway 😂

**Comment by MarcusWolschon** [comment]
In the unfinished, current version on "develop", the 

- changes to the description field of supermarkets doesn't save in editing (but works in creating new ones)
- supermarket descriptions should probably be shown in "supermarkets" tab

**Comment by vabene1111** [comment]
all remaining tasks are enhancements so closing this issue, next release will keep shopping v2 as non default, the release after will deprecate shopping v1 

new issue for remaining enhancements #1649
